name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'mana-ai-lambda/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: il-central-1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and create zip file
        run: |
          cd mana-ai-lambda
          npm install
          zip -r ../lambda-deployment-package.zip .

      - name: Deploy to AWS Lambda
        run: aws lambda update-function-code --function-name handleManaAiCalls --zip-file fileb://lambda-deployment-package.zip
